apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: roohhiit110393/rails_k8s
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: PASSWORD
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: username
                  key: USERNAME
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: port
                  key: PORT
