default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: localhost
  port: 3306
  password: test

development:
  <<: *default
  database: rails_k8s_development

test:
  <<: *default
  database: rails_k8s_test

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSERNAME") %>
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
