default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: localhost
  port: 3306
  password: amagi123

development:
  <<: *default
  database: rails_k8s_production
  username: admin
  host: database-2.cdmxdkzbvdjm.ap-south-1.rds.amazonaws.com
  port: 3306
  password: amagi123

test:
  <<: *default
  database: rails_k8s_test

production:
  <<: *default
  database: rails_k8s_production
  username: admin
  host: database-2.cdmxdkzbvdjm.ap-south-1.rds.amazonaws.com
  port: 3306
  password: amagi123
