apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "backend-ingress"
  namespace: "backend"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    component: backend-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "server-nodeport-service"
              servicePort: 80
